### PR TITLE
Refactor prettier settings

### PR DESCRIPTION
**Pull request by sergiohgz**
**Type:** refactor
**Scope:** all packages except eslint-plugin-verdaccio

The following has been addressed in the PR:

*  There is a related issue? **No**
*  Unit or Functional tests are included in the PR **No**

**Description:** Now, _@verdaccio/eslint-config_ provides a common Prettier settings that were replicated in all projects using it. This allow users the use of `eslint --fix` instead of using Prettier separately. Also, package _@verdaccio/types_ use ESLint to lint declaration files (`.d.ts`).
Finally, I have removed unnecessary scripts like `pretest`, because there is a separated step in both CI we are using, CircleCI and Azure Pipelines.

### CODE REVIEW

**Comment by juanpicado** [comment]
Could you merge from master @sergiohgz ? I'm not sure the recent merge might affect the outcome of this one.

**Comment by sergiohgz** [comment]
Yes, every new package import will fail with these new settings, so we need to merge from master now

**Comment by juanpicado** [comment]
@sergiohgz one `.prettierrc` still there
Screen Shot 2019-08-03 at 4 41 26 PM

**Comment by sergiohgz** [comment]
I will remove that later, `ls` and hidden files 😅

**Pull request merged**
