### PR TITLE
feat(babel-preset): upgrade babel

### PR DESCRIPTION
**Pull request by juanpicado**
**Type:** feat
**Scope:** babel-reset

The following has been addressed in the PR:

*  There is a related issue?
*  Unit or Functional tests are included in the PR

**Description:**

babel to ^7.7.0
https://babeljs.io/blog/2019/11/05/7.7.0

### CODE REVIEW

**Comment by juanpicado** [comment]
```
monorepo/core/streams on  upgrade-babel [$] is 📦 v8.3.0 via ⬢ v10.16.3 at ☸️  docker-desktop 
➜ yarn test
yarn run v1.19.1
$ jest
 FAIL  test/mystreams.spec.ts
  ● Test suite failed to run

    /Users/jpicado/projects/@verdaccio/monorepo/core/streams/src/index.ts:550
      public constructor(options) {
             ^^^^^^^^^^^

    SyntaxError: Unexpected identifier

    > 1 | import { ReadTarball, UploadTarball } from '../src/index';
        | ^
      2 | 
      3 | describe('mystreams', () => {
      4 |   test('should delay events on ReadTarball abort', cb => {

      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (test/mystreams.spec.ts:1:1)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.814s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation abo
```
any idea @sergiohgz ?

**Comment by sergiohgz** [comment]
It should be an issue with a dependency upgraded. I made an update on Sunday for several dependencies and everything looks well. @juanpicado, take a look at https://github.com/verdaccio/monorepo/pull/228

**Comment by sergiohgz** [comment]
Well, I tested merging both branches and it's broken the same way. Looking at the report, it sais that `constructor` is an unexpected identifier, so it seems to be an issue with `@babel/plugin-transform-classes@7.7.0`

**Comment by DanielRuf** [comment]
What was the last clean / working commit and which commit introduced this problem? How can we resolve it?

**Comment by juanpicado** [comment]
@DanielRuf in master works fine, it is just the upgrade to Babel 7.7.0 that creates this issue.

**Comment by DanielRuf** [comment]
Possibly related: https://github.com/babel/babel/issues/10661

**Comment by DanielRuf** [comment]
Can you try to update to 7.7.2 @juanpicado?

**Comment by juanpicado** [comment]
I will try that

**Comment by sergiohgz** [comment]
@juanpicado I've just tested upgrading to latest available versions and it works like a charm. If you have no time, would you want me to amend to your changes and rebase the branch to have it updated? :wink:

**Comment by juanpicado** [comment]
Please would be great :)

**Pull request merged**
