### PR TITLE
fix: return 404 on removePackage

### PR DESCRIPTION
**Pull request by favoyang**
**Type:** bug
**Scope:** aws-s3-storage

The following has been addressed in the PR:

*  There is a related issue? verdaccio/verdaccio/issues/1435
*  Unit or Functional tests are included in the PR. No

**Description:**
Fixed verdaccio/verdaccio/issues/1435, `unpublish -f` failed with s3 storage.

When unpublish a package, verdaccio will remove the package.json and all tarballs, then try to remove (source code use word 'unlink') the directory. It is okay in local storage, but not for s3. S3 does not have the directory concept, when remove all objects under a path, the path is gone as well. So try to remove the directory will returns 404 error. Just ignore the 404 error is fine, and will fix the npm client error.

### CODE REVIEW

**Comment by juanpicado** [comment]
I'll run some test before merge this, I'll work on this.

**Comment by favoyang** [comment]
@juanpicado 

[minio](https://min.io/) is a tool to simulate s3 service on local.

Script to start minio server
```
MINIO_REGION=us-east-1 MINIO_ACCESS_KEY=admin MINIO_SECRET_KEY=password minio server ~/Documents/projects/minio
```
Verdaccio config section
```
store:
  aws-s3-storage:
    bucket: openupm # a folder under minio path
    region: us-east-1
    endpoint: http://127.0.0.1:9000
    accessKeyId: admin
    secretAccessKey: password
    s3ForcePathStyle: true
    keyPrefix: 'verdaccio/'
```

**Comment by juanpicado** [comment]
Thanks that is really helpful 🙏

**Comment by DanielRuf** [comment]
Please describe in the commit message and PR title what it does.

**Comment by juanpicado** [comment]
Try on ` verdaccio-aws-s3-storage@8.5.3`

**Comment by liarco** [comment]
The 404 error is now fixed in my setup (Docker + Digital Oceans's spaces). Thank you everyone!

**Pull request merged**
