### PR TITLE
feat(local-storage): import local-storage package

### PR DESCRIPTION
**Pull request by sergiohgz**
**Type:** feat
**Scope:** local-storage

The following has been addressed in the PR:

*  There is a related issue? **Part of #24**
*  Unit or Functional tests are included in the PR **No**

**Description:** import _@verdaccio/local-storage_ in _plugins/local-storage_

### CODE REVIEW

**Comment by juanpicado** [comment]
🤔 
```
@verdaccio/local-storage:       at findPackages (src/utils.ts:37:10)
@verdaccio/local-storage:       at Object.test (tests/utils.test.ts:61:26)
@verdaccio/local-storage:         Failed to write coverage reports:
@verdaccio/local-storage:         ERROR: TypeError: Cannot read property 'charCodeAt' of null
@verdaccio/local-storage:         STACK: TypeError: Cannot read property 'charCodeAt' of null
```

**Comment by sergiohgz** [comment]
I think that I have introduced a bug, because it is happening in my local machine, but I didn't advise before. I'm going to check it right now :wink:

**Comment by sergiohgz** [comment]
@juanpicado I've just tested and I found that there are 1 test suite failing with 2 tests failed, but this is happening in the original repository. 

I tried in clean environments (3 containers running Node 8, 10 and 12 each) and I discovered a pattern. Try to run the following commands in a container (I recommend next command to remove container after exit: `docker run --rm -it node bash`) and perform next steps:
```bash
# 1. Clone original plugin repo, move to folder and install deps from lockfile
git clone https://github.com/verdaccio/local-storage /local-storage
cd /local-storage
yarn install --frozen-lockfile
# 2. Run tests 2 times, both works fine
yarn test
yarn test
# 3. Run N more time, now tests will fails
yarn test
```
But there is one more thing I noticed between first and second test runs, because both works well but something changed (and I don't mean the times :rofl:). After finishing both, the output have changed:
- After first run
```
Test Suites: 3 passed, 3 total
Tests:       39 passed, 39 total
Snapshots:   0 total
Time:        3.017s
Ran all test suites.
Done in 3.71s.
```
- After second run
```
Test Suites: 3 passed, 3 total
Tests:       39 passed, 39 total
Snapshots:   0 total
Time:        1.415s, estimated 3s
Ran all test suites.
  console.log node_modules/rmdir-sync/index.js:15
    _storage/first-package/package.json

  console.log node_modules/rmdir-sync/index.js:15
    _storage/new-readme-0.0.0.tgz

Done in 2.08s.
```
I suppose they are not causing the errors, but I understand those files are removed before running tests. A better approach should be removing them after they are used, to not leave environmet dirty between test runs.

Should we move this issue to original repository and hold this PR until we have fixed it?

**Comment by sergiohgz** [comment]
I have advanced discovering new behaviours on the problems described above:

1. In `utils.test.ts`, there is a test that breaks coverage reporter, producing the next trace, no matters if any test have failed. I mean the test with description `should handle null read values and return empty database`. This test doesn't fail but if we ignore it, this problem won't appear. Also, when there are cached executions, some unexpected errors occur, like failing tests from other files or don't know how to load `level` module.  
<details>

```
Failed to write coverage reports:
    ERROR: TypeError: Cannot read property 'charCodeAt' of null
    STACK: TypeError: Cannot read property 'charCodeAt' of null
  at stripBOM (internal/modules/cjs/helpers.js:102:15)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:19)
  at Module.load (internal/modules/cjs/loader.js:731:32)
  at Function.Module._load (internal/modules/cjs/loader.js:644:12)
  at Module.require (internal/modules/cjs/loader.js:771:19)
  at require (internal/modules/cjs/helpers.js:68:18)
  at _istanbulLibReport (/workspaces/local-storage/node_modules/@jest/reporters/build/coverage_reporter.js:29:39)
  at /workspaces/local-storage/node_modules/@jest/reporters/build/coverage_reporter.js:232:31
  at Generator.next (<anonymous>)
  at asyncGeneratorStep (/workspaces/local-storage/node_modules/@jest/reporters/build/coverage_reporter.js:124:24)
```
</details>

2. In `utils.test.ts`, there is a complete test suite that fails when there is cached values by jest. That suite has the description `find packages`. If we look the stacktrace without bypassing the error above, we don't find any useful information. But if we ignore that test, the stacktrace becomes more usable.

2.1. `should fails on wrong storage path` test fails because it expect `ENOENT` code but receives `undefined` when there are Jest cache. I don't understand why, but I will try to run on CIs with `--no-cache` to see if it still fails.  
<details>

```
  ● Utitlies › find packages › should fails on wrong storage path

    expect(received).toEqual(expected) // deep equality

    Expected: "ENOENT"
    Received: undefined

      57 |         await findPackages('./no_such_folder_fake', jest.fn(() => true));
      58 |       } catch (e) {
    > 59 |         expect(e.code).toEqual(noSuchFile);
         |                        ^
      60 |       }
      61 |     });
      62 | 

      at Object.toEqual (tests/utils.test.ts:59:24)
```      
</details>

2.2. `should fetch all packages from valid storage` test has some black magic I don't understand. The test is failing in other test file (`local-database.test.ts:172:66`). I think this is caused by an spy don't removed after the test run.  
<details>

```
  ● Utitlies › find packages › should fetch all packages from valid storage

    fails

      170 | 
      171 |     test('should fails on read the storage', done => {
    > 172 |       jest.spyOn(fs, 'readdir').mockImplementation((_, cb) => cb(Error('fails'), null));
          |                                                                  ^
      173 | 
      174 |       const db = new LocalDatabase(
      175 |         assign({}, optionsPlugin.config, {

      at Object.Error (tests/local-database.test.ts:172:66)
      at src/utils.ts:820:13
      at readDirectory (src/utils.ts:812:10)
      at src/utils.ts:877:38
      at findPackages (src/utils.ts:862:10)
      at Object.<anonymous> (tests/utils.test.ts:62:50)
```
</details>

**Comment by sergiohgz** [comment]
I've just discovered the problem with tests. There were a mockImplementation over `fs.readdir` function that wasn't removed after test. When the cache was retrieved to run tests, the mock value returned makes test fails.

Also a fix was required to normalize Windows paths (first normalize and then lowercase them).

**Comment by juanpicado** [comment]
@sergiohgz great job !! In order to do not block you feel free to skip those test that fails.

**Comment by sergiohgz** [comment]
There is no need to skip tests right now, all the big problems were resolved restoring `fs.readdir` mock. I think the problem with coverage write (described before as 1) would be that `@jest/reporters` needs to use that function and the mock were breaking its functionality. This was solved when I resolved the rest of the problems :wink:

**Comment by juanpicado** [comment]
Could you do a `next` release for this package? 🙏 🙃

**Comment by sergiohgz** [comment]
Done @juanpicado, published next packages:
 - verdaccio-google-cloud@8.0.0-next.3
 - @verdaccio/local-storage@8.0.0-next.3

**Pull request merged**
