### PR TITLE
Feature: Custom favicon

### PR DESCRIPTION
**Pull request by AvailCat**
See https://github.com/verdaccio/verdaccio/pull/1787

### CODE REVIEW

**Comment by juanpicado** [comment]
We have a problem ... @sergiohgz ship this under 10.x is not viable now ...

**Comment by sergiohgz** [comment]
Let me create a maintenance branch and move this there

**Comment by sergiohgz** [comment]
Nothing to do, `9.x` branch exists (proof [here](https://github.com/verdaccio/monorepo/tree/9.x)). Please @AvailCat, can you rebase onto that branch?

**Comment by juanpicado** [comment]
> Nothing to do, `9.x` branch exists (proof [here](https://github.com/verdaccio/monorepo/tree/9.x)). Please @AvailCat, can you rebase onto that branch?

Can we safely deploy from there? are no branch filters on CircleCI only for master?

**Comment by AvailCat** [comment]
Done

**Comment by sergiohgz** [comment]
> > Nothing to do, `9.x` branch exists (proof [here](https://github.com/verdaccio/monorepo/tree/9.x)). Please @AvailCat, can you rebase onto that branch?
> 
> Can we safely deploy from there? are no branch filters on CircleCI only for master?
> 
> We might do default branch 9.x while 10.x still in `next`, otherwise future PR will come over `master`.

As I remember, we could deploy from any maintenance branch (N.x or M.N.x), and master branch.

By the way, you are correct, we might change default branch (rename current master to next and make 9.x new master)

**Comment by juanpicado** [comment]
released as `v9.5.0`

**Pull request merged**
