### PR TITLE
docs: aws-s3-storage: modified README.md to add the introduction and few more documentation

### PR DESCRIPTION
**Pull request by ajduke**
**Type:**
Documentation 

**Scope:**

The following has been addressed in the PR:

*  There is a related issue?
No
*  Unit or Functional tests are included in the PR
Not required 

**Description:**

This updates the README for the `aws-s3-storage` plugin

### CODE REVIEW

**Comment by juanpicado** [comment]
Nice ! Do you know whether js is the plugin behavior or part of the AWS sdk logic ?

**Comment by ajduke** [comment]
> Nice ! Do you know whether js is the plugin behavior or part of the AWS sdk logic ?

@juanpicado I did not understand what you are saying.

**Comment by juanpicado** [comment]
> > Nice ! Do you know whether js is the plugin behavior or part of the AWS sdk logic ?
> 
> @juanpicado I did not understand what you are saying.

I mean, those recommendations you are adding, the reason of them is because the plugin behaves in such way or is sdk internal logic?

**Comment by juanpicado** [comment]
ping @ajduke

**Comment by ajduke** [comment]
> ping @ajduke

Thanks for follow-up, I got busy in work related task since 2 months, so, did not get time to work other tasks.

>I mean, those recommendations you are adding, the reason of them is because the plugin behaves in such way or is sdk internal logic?


For your question, plugin behaves this way, as per my testing long back, but let me confirm this again and get back.

**Comment by juanpicado** [comment]
Closing this, code is moved to verdaccio core branch 5.x

**Pull request closed without merging**
