### PR TITLE
Feature/24 add plugin package google cloud

### PR DESCRIPTION
**Pull request by griffithtp**
**Type:** Feature
**Scope:** Plugins - Google Cloud

The following has been addressed in the PR:

*  There is a related issue? **Part of #24**
*  Unit or Functional tests are included in the PR **No**

**Description:**
Import Google Cloud plugins

### CODE REVIEW

**Comment by griffithtp** [comment]
For some reason there are some linting issues. Looking at now.

**Comment by sergiohgz** [comment]
If you are importing from latest master, we added some improvements to ESLint. Also, Prettier requires "endOfLine": "auto" to run on Windows :wink:

**Comment by griffithtp** [comment]
> If you are importing from latest master, we added some improvements to ESLint. Also, Prettier requires "endOfLine": "auto" to run on Windows 😉

Thanks @sergiohgz, I notice .prettierrc is removed from the plugins and is now following #50 
Could you take a look at the build on CircleCI?
Tests work fine locally but on CI
```
verdaccio-google-cloud:   ● Google Cloud Storage › Google Cloud Storage › GoogleCloudStorageHandler:: writeFile › should write a tarball successfully push data |  
-- | --
  | verdaccio-google-cloud:     ENOENT: no such file or directory, open '/home/vsts/work/1/s/plugins/google-cloud/tests/partials/test-pkg/test-pkg-1.0.0.tgz' |  
  | verdaccio-google-cloud:       453 \|         }); |  
  | verdaccio-google-cloud:       454 \| |  
  | verdaccio-google-cloud:     > 455 \|         const bufferFile = fs.readFileSync(tarballFile); |  
  | verdaccio-google-cloud:           \|                               ^ |  
  | verdaccio-google-cloud:       456 \|         const cloudDatabase: ITestLocalData = getCloudDatabase(storageConfig); |  
  | verdaccio-google-cloud:       457 \|         const store: IPackageStorage = cloudDatabase.getPackageStorage(pkgExample.name) as IPackageStorageManager; |  
  | verdaccio-google-cloud:       458 \|         const writeTarballStream = store.writeTarball('test-pkg-1.0.0.tgz'); |  
  | verdaccio-google-cloud:       at Object.readFileSync (tests/storage.spec.ts:455:31)

```

**Comment by sergiohgz** [comment]
There are missing files. Tests on CI are trying to load a tarball but cannot find it. I think it could be because of [this line](https://github.com/verdaccio/monorepo/blob/master/.gitignore#L39).
We have to think on how whitelist every `__tests__` and `tests` folders and all its content

**Comment by sergiohgz** [comment]
I have the solution @griffithtp.

You have to add these lines to `plugins/google-cloud/.gitignore` and add the `.tgz` files:
```
!src/**/__tests__/**/*.tgz
!tests/**/*.tgz
```
The first line will whitelist if we have tests in src file (jest files hierarchy), the second will whitelist in case tests are separated from src folder. 

With these patterns we can add those tgz files we need for testing and avoid to commit the tgz if we make `yarn pack`

**Comment by juanpicado** [comment]
Great job @griffithtp ! 🚀 🚀 🚀 🚀

**Pull request merged**
